feat: add scripts folder and README getting started instructions
acikkaynak/yardim-agi-flutter pull request #16
Opened 2023-02-07 16:27 UTC by adnanjpg

projeye yeni gelen kişilerin hızlıca çalışmaya başlaması için adımları yazdım

2023-02-07 21:19 UTC, easeccy commented
VSCode task'ı kullanarak codegen çalıştırmayı da ekler misin?

2023-02-07 22:02 UTC, adnanjpg commented
@easeccy ekledim bi bakar mısınız olmuş mu, docs'a başka eklememi istediğiniz bir şey var mı?

2023-02-08 11:32 UTC, easeccy commented on .vscode/tasks.json
>              "label": "build_runner main",
add fvm prefix

2023-02-08 11:32 UTC, easeccy commented on .vscode/tasks.json
>              "label": "pub get main",
add fvm prefix

2023-02-08 11:33 UTC, easeccy commented on README.md
> +#### using flutter commands
Using flutter vs fvm şeklinde kategorilendirmek yerine "using bash script" ve "using VSCode commands" olarak kategorilendir.

2023-02-08 11:33 UTC, easeccy requested changes
Fixes needed

2023-02-08 11:52 UTC, adnanjpg commented on README.md
> +#### using flutter commands
`fvm`'i zorunlu kılsak mı çalıştırmak için?

2023-02-08 14:18 UTC, easeccy commented
Tekrar açarsın, şimdilik temizliyorum stale PR ları.

2023-02-08 14:18 UTC, closed without merging